export enum BreedingTransactionEnum {
  CANCEL = "CANCEL",
  NOT_STARTED = "NOT_STARTED",
  PAYMENTED = "PAYMENTED",
  PROCESSING = "PROCESSING",
  FINISHED = "FINISHED",
  WAITING = "WAITING",
  NOT_ULTRASOUND = "NOT_ULTRASOUND",
  PREGNANT = "PREGNANT",
  NOT_PREGNANT = "NOT_PREGNANT",
}

export enum StatusMalePetEnum {
  CANCELED = "CANCELED",
  NOT_AVAILABLE = "NOT_AVAILABLE",
  AVAILABLE = "AVAILABLE",
  READY = "READY",
  NOT_READY = "NOT_READY",
  RETURNED = "RETURNED",
  PAYMENT = "PAYMENT",
}

export enum StatusFemalePetEnum {
  CANCELED = "CANCELED",
  NOT_AVAILABLE = "NOT_AVAILABLE",
  AVAILABLE = "AVAILABLE",
  READY = "READY",
  NOT_READY = "NOT_READY",
  RETURNED = "RETURNED",
}

export enum OrderEnum {
  SUCCESS = "SUCCESS",
  INFOMATION_ERROR = "INFOMATION_ERROR",
  BILLING_ERROR = "BILLING_ERROR",
}

export enum PetEnum {
  DELETED = "DELETED",
  NOT_VERIFIED = "NOT_VERIFIED",
  VERIFIED = "VERIFIED",
  IN_POST = "IN_POST",
}

export enum PostEnum {
  REQUESTED = "REQUESTED",
  CANCELED = "CANCELED",
  PUBLISHED = "PUBLISHED",
  EXPIRED = "EXPIRED",
  DEPOSITED = "DEPOSITED",
}

export enum SaleTransactionEnum {
  PET_AVAILABLE = "PET_AVAILABLE",
  NOT_PET_AVAILABLE = "NOT_PET_AVAILABLE",
  RECEIVED = "RECEIVED",
  NOT_RECEIVED = "NOT_RECEIVED",
  PAYMENTED = "PAYMENTED",
}

export enum GenderEnum {
  MALE = "MALE",
  FEMALE = "FEMALE",
  UNKNOWN = "UNKNOWN",
}

export enum ServiceEnum {
  PURCHASE = "PURCHASE",
  BREED = "BREED",
}
