export enum BreedingTransactionEnum {
  CREATED = "CREATED",
  CANCELED = "CANCELED",
  EXPIRED = "EXPIRED",
  SUCCESS = "SUCCESS",
  BREEDING_REQUESTED = "BREEDING_REQUESTED",
  BREEDING_EXPIRED = "BREEDING_EXPIRED",
  BREEDING_CANCELED = "BREEDING_CANCELED",
  IN_PROGRESS = "IN_PROGRESS",
  BREEDING_FINISHED = "BREEDING_FINISHED",
  BREEDING_SUCCESS = "BREEDING_SUCCESS",
}

export enum SaleTransactionEnum {
  CREATED = "CREATED",
  CANCELED = "CANCELED",
  SUCCESS = "SUCCESS",
  EXPIRED = "EXPIRED",
}

export enum OrderEnum {
  SUCCESS = "SUCCESS",
  WAITING = "WAITING",
  DRAFT = "DRAFT",
}

export enum ComboTypeEnum {
  NORMAL = "NORMAL",
  VACCINE = "VACCINE",
  BREED = "BREED",
  PERIODICAL = "PERIODICAL",
}

export enum PetEnum {
  DELETED = "DELETED",
  NORMAL = "NORMAL",
  IN_POST = "IN_POST",
  IN_BREED = "IN_BREED",
}

export enum PostEnum {
  REQUESTED = "REQUESTED",
  REJECTED = "REJECTED",
  PUBLISHED = "PUBLISHED",
  WAITING_FOR_PAYMENT = "WAITING_FOR_PAYMENT",
  CANCELED = "CANCELED",
  CLOSED = "CLOSED",
}

export enum GenderEnum {
  MALE = "MALE",
  FEMALE = "FEMALE",
  UNKNOWN = "UNKNOWN",
}

export enum ServiceEnum {
  SALE = "SALE",
  BREED = "BREED",
}

export enum PaperEnum {
  CERTIFICATE = "CERTIFICATE",
  PRIZE = "PRIZE",
}

export enum ReportEnum {
  APPROVE = "APPROVE",
  WAITING = "WAITING",
  REJECT = "REJECT",
}

export enum RoleEnum {
  BRANCH_MANAGER = "BRANCH_MANAGER",
  CUSTOMER = "CUSTOMER",
  ADMIN = "ADMIN",
}

export enum RoleIndexEnum {
  BRANCH_MANAGER = 2,
  CUSTOMER = 3,
  ADMIN = 1,
}

export enum LoginStatusEnum {
  SUCCESS = "SUCCESS",
  BANNED = "BANNED",
  NEWER = "NEWER",
  UNAUTHORIZED = "UNAUTHORIZED",
  UNAUTHENTICATED = "UNAUTHENTICATED",
}

export enum PaymentOrderMethodEnum {
  CASH = "CASH",
  VNPAY = "VNPAY",
}

export enum HealthPetRecordEnum {
  VACCINE = "VACCINE",
  HELMINTHIC = "HELMINTHIC",
  TICKS = "TICKS",
}

export enum TicketStatusEnum {
  CREATED = "CREATED",
  CANCELED = "CANCELED",
  SUCCESS = "SUCCESS",
  EXPIRED = "EXPIRED",
}

export enum OrderType {
  DESC = "DESC",
  ASC = "ASC",
}

export enum PostOrderName {
  PROVISIONALTOTAL = "provisionalTotal",
  CREATETIME = "createTime",
}
export enum RoomStatusEnum {
  CREATED = "CREATED",
  BLOCKED = "BLOCKED",
  CLOSED = "CLOSED",
  EXPIRED = "EXPIRED",
  REQUESTED = "REQUESTED",
}

export enum NotificationEnum {
  CONFIRM_POST = "CONFIRM_POST",
  REJECT_POST = "REJECT_POST",
  NEW_ROOM_CREATED = "NEW_ROOM_CREATED",
  NEW_REQUEST = "NEW_REQUEST",
  UPDATE_REQUEST = "UPDATE_REQUEST",
  CANCELED_REQUEST = "CANCELED_REQUEST",
  REJECT_REQUEST = "REJECT_REQUEST",
  APPROVE_REQUEST = "APPROVE_REQUEST",
  CREATED_TICKET = "CREATED_TICKET",
  SUCCESS_SALE_TRANSACTION = "SUCCESS_SALE_TRANSACTION",
  SUCCESS_BREEDING_TRANSACTION = "SUCCESS_BREEDING_TRANSACTION",
  NEW_POST = "NEW_POST",
  AVAILABLE_SERVICE_IN_COMBO = "AVAILABLE_SERVICE_IN_COMBO",
  BREEDING_TRANSACTION_SUCCESS = "BREEDING_TRANSACTION_SUCCESS",
  BREEDING_TRANSACTION_PROGRESSING = "BREEDING_TRANSACTION_PROGRESSING",
  BREEDING_TRANSACTION_FINISHED = "BREEDING_TRANSACTION_FINISHED",
  BREEDING_TRANSACTION_RESULT = "BREEDING_TRANSACTION_RESULT",
}
