name: Pull Req CI

on: [pull_request]

jobs:
    cancel-previous-runs:
        name: Cancel previous runs
        runs-on: ubuntu-latest
        steps:
            - name: Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.4.1
              with:
                  access_token: ${{ github.token }}
    install-deps:
        name: Install dependencies
        continue-on-error: false
        runs-on: ubuntu-latest
        timeout-minutes: 20
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
              with:
                  persist-credentials: false

            - name: Install root dependencies
              run: yarn --frozen-lockfile

            - name: Cache node_modules
              uses: actions/cache@v2
              with:
                  path: |
                      ${{github.workspace}}/node_modules
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
    build:
        name: Build
        continue-on-error: false
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
              with:
                  persist-credentials: false
            - name: Restore Deps
              uses: actions/cache@v2
              id: restore-deps
              with:
                  path: |
                      ${{github.workspace}}/node_modules
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
            - name: Restore Build
              uses: actions/cache@v2
              id: restore-build
              with:
                  path: "**/build"
                  key: ${{ runner.os }}-build-${{ github.sha }}

            - name: Build
              run: |
                yarn build